name: connectme
description: Framework for console server applications
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  packme:
    git: https://github.com/sourcecaster/packme.git
