name: connectme
description: WebSocket connection management library to handle client-server communication in event-based manner or await-query style (using PackMe messages).
version: 1.1.1
homepage: https://github.com/sourcecaster/connectme
repository: https://github.com/sourcecaster/connectme
issue_tracker: https://github.com/sourcecaster/connectme/issues
documentation: https://github.com/sourcecaster/connectme
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  packme: ^1.1.5
dev_dependencies:
  test: ^1.17.11