name: connectme
description: WebSocket connection management library to handle client-server communication in event-based manner or await-query style (using PackMe messages).
version: 2.2.2
homepage: https://github.com/sourcecaster/connectme
repository: https://github.com/sourcecaster/connectme
issue_tracker: https://github.com/sourcecaster/connectme/issues
documentation: https://github.com/sourcecaster/connectme
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  packme: ^2.0.1
dev_dependencies:
  test: ^1.24.6